# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sparrow-hawk-images"
BBFILE_PATTERN_sparrow-hawk-images = "^${LAYERDIR}/"
BBFILE_PRIORITY_sparrow-hawk-images = "6"
LAYERSERIES_COMPAT_sparrow-hawk-images = "scarthgap"
LAYERDEPENDS_sparrow-hawk-images = "core openembedded-layer meta-python sparrow-hawk-bsp"
