name: Setup build environment
description: Setup build environment for Sparrow Hawk BSP
runs:
  using: "composite"
  steps:
    - name: Free runner space
      uses: justinthelaw/maximize-github-runner-space@c66ba0f3ad90f3f74aa2250d8ea645080be24da3 # v0.12.3
      with:
        swapfile-size: 8GiB

    - name: Setup package
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping \
          libacl1 liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect \
          python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd device-tree-compiler
        # Clean up apt
        sudo apt autoremove -y
        sudo apt clean -y
        sudo apt autoclean -y
        # For using --sstate-mirror option
        pip3 install websockets
        df -h

    - name: WA for Ubuntu 24.04
      shell: bash
      run: |
        UBUNTU_VERSION="$(cat /etc/os-release | grep VERSION_ID | cut -d'"' -f2)"
        if [[ "${UBUNTU_VERSION}" == "24.04" ]]; then
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          sudo apparmor_parser -R /etc/apparmor.d/unprivileged_userns
        fi

    - name: Check disk and memory
      shell: bash
      run: |
        ls -lh
        df -h
        free -h


